name: Build Docker Image and Export as Tar

# 触发条件：在 master 分支推送时运行
on:
  push:
    branches:
      - master

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      # 步骤 1：检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2：设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 步骤 3：构建 Docker 镜像
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: docker/  # 指定 Dockerfile 所在目录
          file: docker/Dockerfile  # 指定 Dockerfile 路径
          tags: my-app:latest  # 镜像名和标签
          push: false  # 不推送镜像，仅本地构建
          load: true  # 将镜像加载到本地 Docker 守护进程

      # 步骤 4：将镜像保存为 .tar 文件
      - name: Save Docker Image as Tar
        run: |
          docker save -o my-app-latest.tar my-app:latest
          ls -lh my-app-latest.tar

      # 步骤 5：上传 .tar 文件作为 artifact
      - name: Upload Docker Image Tar as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-latest-tar
          path: my-app-latest.tar
          retention-days: 7  # 保留 7 天