name: Build Export Image from Dockerfile

on:
  workflow_dispatch:  # 仅允许手动触发工作流
    inputs:
      image_name:  # 定义输入参数：镜像名称
        description: 'Name of the Docker image (without tag)'
        required: true
        default: 'Ubuntu-ffmpeg-amd64'  # 默认镜像名称
      image_tag:  # 定义输入参数：镜像标签
        description: 'Tag of the Docker image'
        required: true
        default: 'v1.0'  # 默认镜像标签
      tar_name:  # 定义输入参数：tar 文件名
        description: 'Name of the tar file (without .tar extension)'
        required: true
        default: 'Ubuntu-ffmpeg-amd64'  # 默认 tar 文件名
      platform:  # 输入参数：目标平台
        description: 'Target platform for the Docker image (amd or arm)'
        required: false  # 设为可选
        default: 'amd'  # 默认平台为 amd
      context_dir:  # 输入参数：构建上下文目录
        description: 'Directory containing the Dockerfile (e.g., ., test)'
        required: false  # 设为可选
        default: '.'  # 默认上下文目录为根目录

jobs:
  build-and-export:
    runs-on: ubuntu-latest  # 使用 Ubuntu 运行器

    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 QEMU（支持多平台构建）
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all  # 支持所有平台（包括 amd64 和 arm64）

      # 3. 设置 Docker Buildx（支持多平台构建）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 确定平台和 Dockerfile 路径
      - name: Determine Platform and Dockerfile Path
        id: setup
        run: |
          PLATFORM_INPUT="${{ github.event.inputs.platform || 'amd' }}"
          # 将用户输入的 platform 转换为完整的平台格式（amd -> linux/amd64, arm -> linux/arm64）
          if [ "$PLATFORM_INPUT" = "amd" ]; then
            FULL_PLATFORM="linux/amd64"
          elif [ "$PLATFORM_INPUT" = "arm" ]; then
            FULL_PLATFORM="linux/arm64"
          else
            echo "Invalid platform: $PLATFORM_INPUT. Must be 'amd' or 'arm'."
            exit 1
          fi
          echo "full_platform=$FULL_PLATFORM" >> $GITHUB_OUTPUT

          CONTEXT_DIR="${{ github.event.inputs.context_dir || '.' }}"
          # 检查是否存在特定平台的 Dockerfile（例如 Dockerfile.amd 或 Dockerfile.arm）
          if [ -f "$CONTEXT_DIR/Dockerfile.$PLATFORM_INPUT" ]; then
            echo "dockerfile_path=$CONTEXT_DIR/Dockerfile.$PLATFORM_INPUT" >> $GITHUB_OUTPUT
          elif [ -f "$CONTEXT_DIR/Dockerfile" ]; then
            echo "dockerfile_path=$CONTEXT_DIR/Dockerfile" >> $GITHUB_OUTPUT
          else
            echo "No Dockerfile found in $CONTEXT_DIR for platform $PLATFORM_INPUT"
            exit 1
          fi

      # 5. 构建 Docker 镜像（使用用户选择的上下文目录和平台）
      - name: Build Docker Image for Selected Platform
        uses: docker/build-push-action@v5
        with:
          context: ${{ github.event.inputs.context_dir || '.' }}  # 使用输入参数指定构建上下文目录
          file: ${{ steps.setup.outputs.dockerfile_path }}  # 使用动态确定的 Dockerfile 路径
          platforms: ${{ steps.setup.outputs.full_platform }}  # 使用转换后的完整平台
          tags: ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}  # 使用输入参数设置镜像名称和标签
          push: false  # 不推送镜像
          load: true  # 将镜像加载到本地（以便后续保存为 tar）

      # 6. 将 Docker 镜像保存为 tar 文件
      - name: Save Docker Image as Tar
        run: |
          docker save -o ${{ github.event.inputs.tar_name }}-${{ steps.setup.outputs.full_platform }}.tar ${{ github.event.inputs.image_name }}:${{ github.event.inputs.image_tag }}
          ls -lh ${{ github.event.inputs.tar_name }}-${{ steps.setup.outputs.full_platform }}.tar

      # 7. 上传 Docker 镜像 tar 文件作为工件
      - name: Upload Docker Image Tar as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.tar_name }}-${{ github.event.inputs.image_tag }}-${{ steps.setup.outputs.full_platform }}-tar  # 在工件名称中包含平台信息
          path: ${{ github.event.inputs.tar_name }}-${{ steps.setup.outputs.full_platform }}.tar  # 在 tar 文件路径中包含平台信息
          retention-days: 2  # 工件保留 2 天
